### ISSUE TITLE
Future development of pymee

### ISSUE THREAD

**Issue by Taraman17** [FreshlyBrewedCode/pymee#15]
Hi,

I'm planning some bigger changes to pymee in the near future:
- support more message types (error, user, settings)
- use enum classes in const.py
- refactor code so HA integration does not need to use private properties

Do you still want to  be kept in the loop and do it via Pull requests -> release by you or shall we do it the same way as with the HA integration?

**Comment by FreshlyBrewedCode** [comment]
Hi, I can not guarantee that I will check GitHub regularly and merge PRs in a time frame that is acceptable to you. Feel free to continue development in your fork. Alternatively, I could also add you as a contributor to this repo so you can merge PRs yourself.

**Comment by Taraman17** [comment]
Let's try the second option. That way it still stays your application - you did the most part of the work on it.

**Comment by Taraman17** [comment]
Thank you, just tested a pull-request to develop branch to see if it works.
