### ISSUE TITLE
Fix publishing to PyPi

### ISSUE THREAD

**Issue by Taraman17** [FreshlyBrewedCode/pymee#26]
The upload to PyPi fails in the release process:

400 User 'FreshlyBrewedCode' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.

**Comment by Taraman17** [comment]
And sorry for all the push-spam ;-)

**Comment by Taraman17** [comment]
I know these things get easily forgotten if they are a few days past.
So just a friendly little reminder. ;-)

**Comment by FreshlyBrewedCode** [comment]
Should be fixed.

**Comment by Taraman17** [comment]
Danke, werde es die Tage probieren

**Comment by Taraman17** [comment]
Klappt, danke nochmal.
