### ISSUE TITLE
NodeProtocol 28 is Virtual Device, should be added

### ISSUE THREAD

**Issue by wisemanny** [FreshlyBrewedCode/pymee#32]
I see homee added Virtual Devices (that you can control via set_value). Their NodeProtocol ID is 28, should be added somewhere here: https://github.com/FreshlyBrewedCode/pymee/blob/master/pymee/const.py#L182

I do not know the right const name, would call is "VIRTUAL_DEVICE". I can do a PR later, but it's not convenient right now.

**Comment by Taraman17** [comment]
I will add it in the next release.

**Comment by Taraman17** [comment]
This issue is fixed in release 2.3.0, but since the publishing to pypi is broken, it is not yet available for install via pip.

**Comment by Taraman17** [comment]
publishing is moved to other repo, closing here.
